### ISSUE TITLE
Link styling/behavior on the home table

### ISSUE THREAD

**Issue by alexjpujol** [MSCSHub/MSCSHub#100]
I'd like to propose a couple small UX changes for the home page:

1) make the course titles the link to the individual course views rather than the entire row
2) add styling when hovering on the course title (cursor:pointer, underline/bold the title)

Happy to put up a PR if you think these are worth adding

**Comment by estraw1059** [comment]
Hey Alex,

I personally like that you can click on the entire row to get to the classes. I don't know how @EricPryzant feels about that. I do like the hovering idea though. Feel free to PR if you have something. We are both working full time now and don't have as much time to add to the site. If you see anything else feel free to post here or slack me on the MSCS slack.

**Comment by alexjpujol** [comment]
ok cool I can put something up for 2, i think doing 2 would probably make 1 unnecessary anyway

**Comment by EricPryzant** [comment]
Hey, thanks for the ideas. I think they are worth discussing further though it's important to understand why we decided to do it this way. A lot of it revolves around ensuring the mobile user experience is just as great as the desktop experience. To that end, it's really helpful for mobile users to be able to click anywhere since they can't see the full table row in their screen and should be able to select a row without needing to scroll all the way back to the left. 

Your second point has merit and I'm interested to see what ideas you have for improving the styling. I look forward to seeing what you propose.

**Comment by EricPryzant** [comment]
Our process on this repo for making changes is to 
1. Open an issue 
2. Document your ideas and proposed changes. Labeling it also helps <------ We're at this stage
3. Assign this issue to yourself. This creates a branch automatically
4. Make your changes within your branch
5. Create a pull request
6. Get signoff from the required reviewers and merge the changes
7. The repo owner (me) will deploy the changes once the PR is merged

**Comment by EricPryzant** [comment]
There hasn't been any activity on this so I'm closing this for the time being. Feel free to reopen this item @alexjpujol if you want to work on it
