### ISSUE TITLE
Suspicious rating for textbook

### ISSUE THREAD

**Issue by rvdg** [MSCSHub/MSCSHub#101]
The textbook for Natural Language Processing currently gets a score of 0.8 on a scale from 1-7.  I think there is a bug...

**Comment by EricPryzant** [comment]
@rvdg The class receives this score because, even though there is a textbook, it is never referenced during lecture. The system that we implemented asks our users to rate a course's textbook as a zero if there is no textbook. To illustrate how this affects the rating, we have four reviews for NLP with one rating of 3/7 and the rest saying there was No Textbook.

This is not a bug though it is a defect in the system that we are using to rate the textbook.
